name: BC-Linter Tests

on:
  pull_request:
    paths:
      - .github/workflows/bc-linter-tests.yml
      - tools/stronghold/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/bc-linter-tests.yml
      - tools/stronghold/**

defaults:
  run:
    working-directory: tools/stronghold/

jobs:
  bc-linter-tests:
    name: BC-Linter Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run BC-Linter tests
        run: python -m pytest tests/ -v
