name: Lambda Runner Binaries Syncer
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/lambda-runner-binaries-syncer.yml
      - "terraform-aws-github-runner/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/**"

jobs:
  build:
    name: "Run tests for runner binaries syncer lambda"
    runs-on: ubuntu-latest
    container: node:20
    defaults:
      run:
        working-directory: terraform-aws-github-runner/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Build, Lint, and Test
        run: make build
