name: Lambda Runners
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/lambda-runners.yml
      - "terraform-aws-github-runner/modules/runners/lambdas/runners/**"

jobs:
  build:
    name: "Run tests for runners lambda"
    runs-on: ubuntu-latest
    container: node:20
    defaults:
      run:
        working-directory: terraform-aws-github-runner/modules/runners/lambdas/runners

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Build, Lint, and Test
        run: make build
