name: TFLint
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/tflint.yml"
      - "terraform-aws-github-runner/**"

jobs:
  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    container: node:20

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      name: Checkout source code

    - uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4.1.1
      name: Setup TFLint
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tflint_version: v0.54.0

    - name: Install Tofu
      uses: opentofu/setup-opentofu@9d84900f3238fab8cd84ce47d658d25dd008be2f # v1.0.8
      with:
        terraform_version: 1.5.7
        terraform_wrapper: false

    - name: Show tflint version
      run:
        tflint --version

    - name: Show tofu version
      run:
        tofu --version

    - name: "tflint"
      working-directory: terraform-aws-github-runner
      run: make tflint
