name: Update queue times dataset

on:
  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch:

defaults:
  run:
    working-directory: torchci
jobs:
  update-queue-times:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: yarn install --frozen-lockfile
      - name: configure aws credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0 # v3.0.2
        with:
          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_update_queue_times
          aws-region: us-east-1
      - run: yarn node scripts/updateQueueTimes.mjs
        env:
          HUD_API_TOKEN: ${{ secrets.HUD_API_TOKEN }}
